version: '3'

services:
  app:
    image: trekko_server:latest
    build: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: trekko
